apiVersion: apps/v1
kind: Deployment
metadata:
  name: charizard
  labels:
    app: charizard
spec:
  replicas: 3
  selector:
    matchLabels:
      app: charizard
  template:
    metadata:
      labels:
        app: charizard
    spec:
      containers:
        - name: charizard
          image: REPLACE_IMAGE_TAG
          imagePullPolicy: Always 
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_SERVICE_HOST
              value: "10.16.1.24"
            - name: MY_MONGO_PORT
              value: "27017"
---
apiVersion: v1
kind: Service
metadata:
  name: charizard-service
spec:
  selector:
    app: charizard
  ports:
    - protocol: TCP
      port: 80         # Exposed port (can be any valid port number)
      targetPort: 8080 # Port your application listens on inside the pod
  type: LoadBalancer  # Use "LoadBalancer" to create a Load Balancer