name: Deploy to GKE
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GCP environment
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker to use the GCP credential helper
        run: |
          gcloud auth configure-docker

      - name: Apply Kubernetes YAML files
        run: |
          kubectl apply -f kube/mongodb-deployment.yaml
          kubectl apply -f kube/nodejs-app-deployment.yaml
