name: Deploy Pac-Man

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 6.9.0

      - name: Start MongoDB
        run: sudo systemctl start mongod

      - name: Deploy to Linux VM
        run: |
          cd /home/jedidiah/pacman
          npm install
          npm run start
