name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    
  GKE_ZONE: asia-southeast1   
  IMAGE_REPO: jlimhy/charizard
  TAG: ${{ github.sha }}

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authentication with SA Key
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

  build_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_REPO:$TAG .
          docker push $IMAGE_REPO:$TAG

  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest
    needs: [setup, build_push]
    steps:
      - name: Get GKE Credentials
        uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY }}

      - name: Apply MongoDB Deployment
        run: kubectl apply -f mongodb-deployment.yaml

      - name: Apply Node.js App Deployment
        run: kubectl apply -f nodejs-app-deployment.yaml