name: Docker Build & Push & Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    
  GKE_ZONE: asia-southeast1   
  IMAGE_REPO:  ${{ secrets.DOCKER.HUB.USERNAME }}/charizard
  VERSION_TAG: ${{ env.VERSION_TAG }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production   
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Authentication with Service Account Key
    - name: Authentication with SA Key
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    # Get the GKE credentials so we can deploy to the cluster
    - name: GKE Credentials 
      uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Build & push Docker image to Docker Hub
    - name: Build and push Docker image
      run: |
        docker build -t ${{ env.IMAGE_REPO }}:${{ env.VERSION_TAG }} .
        docker push ${{ env.IMAGE_REPO }}:${{ env.VERSION_TAG }}

    # Deploy the updated Docker image to the GKE cluster
    - name: Deploy Database & Pacman
      run: |-
        kubectl apply -f mongodb-deployment.yaml
        kubectl apply -f nodejs-app-deployment.yaml
