name: Docker Build & Push & Build and Deploy to GKE
on:
  push:
    branches:
      - main
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: autopilot-cluster-1    
  GKE_ZONE: asia-southeast1   
jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production   
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: GKE JSON
      run: |
        access_key=$(cat ${{ secrets.GKE_SA_KEY }} | base64)
        echo "::add-mask::$access_key"      
        echo "GKE_SA=$access_key" >> "$GITHUB_ENV"
      

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
      with:
        project_id: ${{ secrets.GKE_PROJECT }}
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ env.GKE_SA }}

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t jlimhy/charizard:latest .
        docker push jlimhy/charizard:latest    

      # Deploy the first Docker image to the GKE cluster
    - name: Deploy Database & Pacman
      run: |-
        kubectl apply -f mongodb-deployment.yaml
        kubectl apply -f nodejs-app-deployment.yaml
